apiVersion: v2
appVersion: v2.13.0
description: A Helm chart for a test app
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
home: https://github.com/giantswarm/test-app
name: test-app
version: 1.0.1
annotations:
  io.giantswarm.application.team: honeybadger
